baseURL = "https://nadjet.github.io"
publishDir = "docs"
languageCode = "en-us"
title = "Nadjet's NLP Stuff"
theme = "beautifulhugo"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about me"
    name = "about me"
    url = "about/"
    weight = 40

